name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system & Python deps
        run: |
          apt-get update && apt-get install -y gcc libpq-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest pytest-cov psycopg2-binary

      # IMPORTANT: when you run your job in a container, the Postgres service hostname is 'postgres' (the service name), not 'localhost'
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            if pg_isready -h postgres -p 5432; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Set DB env for tests
        run: |
          echo "DATABASE_URL=postgresql://postgres:pgs3cr3t@postgres:5432/testdb" >> $GITHUB_ENV
          echo "DATABASE_URI=postgresql://postgres:pgs3cr3t@postgres:5432/testdb" >> $GITHUB_ENV

      - name: Lint
        run: |
          flake8 .
          black --check .

      - name: Test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DATABASE_URI: ${{ env.DATABASE_URI }}
          FLASK_ENV: testing
        run: pytest -q --maxfail=1 --disable-warnings --cov=service --cov-report=term-missing
